@extends('site::layouts.public')

{{-- SEO meta is generated by site::partials.head-meta directly. --}}

@section('content')
@php
    $locale = app()->getLocale();
    $coverImage = $page->featured_image;
@endphp

<article class="bg-white text-vmta-teal">
    <header class="relative min-h-[300px] overflow-hidden bg-vmta-teal">
        @if($coverImage)
            <img src="{{ $coverImage }}" alt="" class="absolute inset-0 h-full w-full object-cover opacity-35" loading="eager" decoding="async">
        @endif
        <div class="absolute inset-0 bg-vmta-teal/75"></div>

        <div class="relative mx-auto flex min-h-[300px] max-w-7xl flex-col items-center justify-end px-4 pb-9 text-center">
            <h1 class="max-w-[1210px] font-sharp-bo text-[24px] font-bold uppercase leading-[1.08] text-white sm:text-[28px] lg:text-[34px]">
                {{ $translation->title }}
            </h1>
            <nav class="mt-5 text-[15px] leading-6 text-white" aria-label="Breadcrumb">
                <a href="{{ route('site.'.$locale.'.content.home') }}" class="text-white">{{ $locale === 'vi' ? 'Trang chủ' : 'Home' }}</a>
                <span> / </span>
                <span>{{ $translation->title }}</span>
            </nav>
        </div>
    </header>

    <div class="mx-auto max-w-7xl px-4 pb-[80px] pt-6">
        @if($translation->excerpt)
            <p class="text-[18px] leading-[1.7] text-vmta-teal">
                {{ $translation->excerpt }}
            </p>
        @endif

        <div class="prose prose-lg mt-6 max-w-none text-vmta-teal prose-headings:font-sharp-bo prose-headings:text-vmta-teal prose-a:text-vmta-teal prose-strong:text-vmta-teal prose-img:w-full prose-img:max-w-full prose-img:rounded-none">
            {{-- Body purified via mews/purifier (config/purifier.php "default" profile) so <script>,
                 on*-event handlers, and javascript:-scheme URLs are stripped even from admin paste. --}}
            {!! clean($translation->body ?? '') !!}
        </div>
    </div>
</article>
@endsection
