@extends('site::layouts.public')

{{-- SEO meta is generated by site::partials.head-meta directly. --}}

@section('content')
@php
    $locale = app()->getLocale();
    $postItems = $posts->getCollection();
    $featuredPost = $postItems->last() ?? $postItems->first();
    $smallPosts = $featuredPost ? collect([$featuredPost, $featuredPost]) : collect();
    $editorName = $locale === 'vi' ? 'Biên Tập Viên' : 'Editor';

    $fallbackImages = [
        'thu-truong-bo-y-te-tran-van-thuan-cung-voi-dinh-vi-thuong-hieu-quoc-gia-can-da-dang-phuong-thuc-truyen-thong-ve-phat-trien-du-lich-y-te'
            => asset('images/news/thu-truong-bo-y-te-tran-van-thuan.png'),
        'thu-truong-bo-y-te-tran-van-thuan-cung-voi-dinh-vi-thuong-hieu-quoc-gia'
            => asset('images/news/thu-truong-bo-y-te-tran-van-thuan.png'),
        'lien-minh-du-lich-y-te-viet-nam-ra-mat-danh-thuc-tiem-nang-thi-truong-ty-usd'
            => asset('images/news/lien-minh-du-lich-y-te-ra-mat.jpg'),
        'lien-minh-du-lich-y-te-viet-nam-ra-mat'
            => asset('images/news/lien-minh-du-lich-y-te-ra-mat.jpg'),
        'making-vietnam-a-leading-medical-tourism-destination'
            => asset('images/news/making-vietnam-medical-tourism.webp'),
    ];

    $postTranslation = fn ($post) => $post->translations->firstWhere('locale', $locale) ?? $post->translations->first();
    $postUrl = fn ($tr) => route('site.'.$locale.'.content.posts.show', ['slug' => $tr?->slug]);
    $postImage = fn ($post, $tr) => $post->featured_image
        ?: ($fallbackImages[$tr?->slug] ?? asset('images/news/making-vietnam-medical-tourism.webp'));
@endphp

<section class="relative h-[300px] overflow-hidden bg-white">
    <img src="{{ asset('images/about/8cae972b-1b32-4567-b3e9-d7348ea691af.png') }}"
         alt="" class="absolute inset-0 h-full w-full object-cover opacity-20" loading="eager" decoding="async">
    <div class="relative mx-auto flex h-full max-w-7xl flex-col justify-end px-4 py-4">
        <h1 class="font-sharp-bo text-[46px] font-bold uppercase leading-none text-vmta-teal md:text-[50px]">
            {{ __('content::public.news_heading') }}
        </h1>
        <p class="mt-2 text-[16px] text-vmta-teal">
            {{ $locale === 'vi' ? 'Trang chủ / Tin tức' : 'Home / News' }}
        </p>
    </div>
</section>

<section class="bg-white pt-[30px] pb-[64px]">
    <div class="mx-auto max-w-7xl px-4">
        @if($postItems->isEmpty())
            <p class="text-vmta-teal">{{ __('content::public.no_posts_yet') }}</p>
        @else
            <div class="grid grid-cols-1 gap-[28px] lg:grid-cols-[621px_1fr]">
                @if($featuredPost)
                    @php
                        $featuredTr = $postTranslation($featuredPost);
                        $featuredImage = $postImage($featuredPost, $featuredTr);
                    @endphp
                    <div>
                        <article class="relative overflow-hidden bg-[#d4eceb]">
                            <a href="{{ $postUrl($featuredTr) }}" aria-label="{{ $featuredTr?->title }}">
                                <img src="{{ $featuredImage }}" alt="{{ $featuredTr?->title }}"
                                     class="aspect-[16/10] w-full object-cover" loading="lazy" decoding="async">
                                <div class="absolute inset-0 flex flex-col justify-end bg-gradient-to-b from-[#0775720d] via-[#0775728a] to-[#077572f2] px-4 pb-4">
                                    <h2 class="max-w-[92%] text-[26px] font-bold leading-[1.15] text-white max-md:text-[22px]">
                                        {{ $featuredTr?->title }}
                                    </h2>
                                </div>
                            </a>
                        </article>

                        <div class="mt-2.5 grid grid-cols-2 gap-2.5 sm:grid-cols-2 md:grid-cols-3">
                            @foreach($smallPosts as $smallPost)
                                @php
                                    $smallTr = $postTranslation($smallPost);
                                    $smallImage = $postImage($smallPost, $smallTr);
                                @endphp
                                <article>
                                    <a href="{{ $postUrl($smallTr) }}" aria-label="{{ $smallTr?->title }}"
                                       class="block overflow-hidden bg-[#d4eceb]">
                                        <img src="{{ $smallImage }}" alt="{{ $smallTr?->title }}"
                                             class="aspect-[16/10] w-full object-cover" loading="lazy" decoding="async">
                                    </a>
                                    <h3 class="mt-[5px] bg-[#69ccc7] p-[15px] text-[14px] font-bold leading-[1.3]">
                                        <a href="{{ $postUrl($smallTr) }}" class="line-clamp-2 text-[#064744]">
                                            {{ $smallTr?->title }}
                                        </a>
                                    </h3>
                                </article>
                            @endforeach
                        </div>
                    </div>
                @endif

                <aside class="flex min-h-full flex-col pt-1">
                    <h2 class="mb-5 font-sharp-bo text-[30px] font-bold uppercase leading-none text-vmta-teal">
                        {{ $locale === 'vi' ? 'Tin mới' : 'Latest News' }}
                    </h2>
                    <ul class="flex flex-1 flex-col">
                        @foreach($postItems->take(3) as $i => $post)
                            @php $tr = $postTranslation($post); @endphp
                            <li class="{{ $i === 0 ? 'bg-vmta-teal' : '' }} px-[14px] py-2.5 text-[17px] font-bold leading-[1.2]">
                                <a href="{{ $postUrl($tr) }}" class="{{ $i === 0 ? 'text-white' : 'text-vmta-teal' }}">
                                    {{ $tr?->title }}
                                </a>
                            </li>
                        @endforeach
                    </ul>
                </aside>
            </div>

            <section class="mt-[60px]">
                <h2 class="mb-5 font-sharp-bo text-[30px] font-bold uppercase leading-none text-vmta-teal">
                    {{ $locale === 'vi' ? 'Bài viết' : 'Posts' }}
                </h2>
                <div class="grid grid-cols-1 gap-x-4 gap-y-5 md:grid-cols-2">
                    @foreach($postItems as $post)
                        @php
                            $tr = $postTranslation($post);
                            $image = $postImage($post, $tr);
                            $author = $post->author?->name ?: $editorName;
                        @endphp
                        <article class="m-0">
                            <a href="{{ $postUrl($tr) }}" aria-label="{{ $tr?->title }}"
                               class="block overflow-hidden bg-[#d4eceb]">
                                <img src="{{ $image }}" alt="{{ $tr?->title }}"
                                     class="aspect-[16/10] w-full object-cover" loading="eager" decoding="async">
                            </a>
                            <h3 class="mt-1.5 text-[20px] font-bold leading-[1.3] text-vmta-teal">
                                <a href="{{ $postUrl($tr) }}" class="text-vmta-teal">
                                    {{ $tr?->title }}
                                </a>
                            </h3>
                            @if($tr?->excerpt)
                                <p class="mt-1 line-clamp-2 text-[16px] leading-[1.45] text-vmta-teal">
                                    {{ $tr->excerpt }}
                                </p>
                            @endif
                            <div class="mt-1.5 flex items-center justify-between gap-2.5 text-[16px] text-vmta-teal max-sm:flex-col max-sm:items-start">
                                <a href="{{ $postUrl($tr) }}" class="text-vmta-teal">{{ $locale === 'vi' ? 'Xem thêm >' : 'Read more >' }}</a>
                                @if($post->published_at)
                                    <span>
                                        <time datetime="{{ $post->published_at->toDateString() }}">{{ $post->published_at->format('d/m/Y') }}</time>
                                        <span> | </span>
                                        <span>{{ $author }}</span>
                                    </span>
                                @endif
                            </div>
                        </article>
                    @endforeach
                </div>

                <div class="mt-8">{{ $posts->links() }}</div>
            </section>
        @endif
    </div>
</section>
@endsection
