@extends('site::layouts.public')

{{-- SEO meta is generated by site::partials.head-meta directly. --}}

@section('content')
@php
    $locale = app()->getLocale();
    $editorName = $locale === 'vi' ? 'Biên Tập Viên' : 'Editor';

    $fallbackImages = [
        'thu-truong-bo-y-te-tran-van-thuan-cung-voi-dinh-vi-thuong-hieu-quoc-gia-can-da-dang-phuong-thuc-truyen-thong-ve-phat-trien-du-lich-y-te'
            => asset('images/news/thu-truong-bo-y-te-tran-van-thuan.png'),
        'thu-truong-bo-y-te-tran-van-thuan-cung-voi-dinh-vi-thuong-hieu-quoc-gia'
            => asset('images/news/thu-truong-bo-y-te-tran-van-thuan.png'),
        'lien-minh-du-lich-y-te-viet-nam-ra-mat-danh-thuc-tiem-nang-thi-truong-ty-usd'
            => asset('images/news/lien-minh-du-lich-y-te-ra-mat.jpg'),
        'lien-minh-du-lich-y-te-viet-nam-ra-mat'
            => asset('images/news/lien-minh-du-lich-y-te-ra-mat.jpg'),
        'making-vietnam-a-leading-medical-tourism-destination'
            => asset('images/news/making-vietnam-medical-tourism.webp'),
    ];

    $postTranslation = fn ($item) => $item->translations->firstWhere('locale', $locale) ?? $item->translations->first();
    $postUrl = fn ($tr) => route('site.'.$locale.'.content.posts.show', ['slug' => $tr?->slug]);
    $postImage = fn ($item, $tr) => $item->featured_image
        ?: ($fallbackImages[$tr?->slug] ?? asset('images/news/making-vietnam-medical-tourism.webp'));

    $coverImage = $postImage($post, $translation);
    $authorName = $post->author?->name ?: $editorName;
    // post_body profile keeps headings/tables/iframes + <video data-hls-src> for HLS streams.
$cleanBody = clean($translation->body ?? '', 'post_body');

// Enhance HLS <video> tags: add autoplay/loop/muted/poster + full-width rounded styling (matches vmta.vn UX).
$cleanBody = preg_replace_callback(
    '/<video\b([^>]*?)\bdata-hls-src="([^"]+)"([^>]*?)>/i',
    function ($m) use ($coverImage) {
        $posterAttr = $coverImage ? ' poster="'.e($coverImage).'"' : '';
        return '<video playsinline muted autoplay loop controls'.$posterAttr
            .' style="width:100%; border-radius:12px;"'
            .' data-hls-src="'.e($m[2]).'">';
    },
    $cleanBody
);

$hasHlsVideo = str_contains($cleanBody, 'data-hls-src');
@endphp

<article class="bg-white text-vmta-teal">
    <header class="relative min-h-[300px] overflow-hidden bg-vmta-teal">
        <img src="{{ $coverImage }}" alt="" class="absolute inset-0 h-full w-full object-cover opacity-35" loading="eager" decoding="async">
        <div class="absolute inset-0 bg-vmta-teal/75"></div>

        <div class="relative mx-auto flex min-h-[300px] max-w-7xl flex-col items-center justify-end px-4 pb-9 text-center">
            <h1 class="max-w-[1210px] font-sharp-bo text-[24px] font-bold uppercase leading-[1.08] text-white sm:text-[28px] lg:text-[34px]">
                {{ $translation->title }}
            </h1>
            <nav class="mt-5 text-[15px] leading-6 text-white" aria-label="Breadcrumb">
                <a href="{{ route('site.'.$locale.'.content.home') }}" class="text-white">{{ $locale === 'vi' ? 'Trang chủ' : 'Home' }}</a>
                <span> / </span>
                <a href="{{ route('site.'.$locale.'.content.posts.index') }}" class="text-white">{{ $locale === 'vi' ? 'Tin tức' : 'News' }}</a>
                <span> / </span>
                <span>{{ $translation->title }}</span>
            </nav>
        </div>
    </header>

    <div class="mx-auto max-w-7xl px-4 pb-[80px] pt-6">
        @if($translation->excerpt)
            <p class="text-[18px] leading-[1.7] text-vmta-teal">
                {{ $translation->excerpt }}
            </p>
        @endif

        <div class="prose prose-lg mt-6 max-w-none text-vmta-teal prose-headings:font-sharp-bo prose-headings:text-vmta-teal prose-a:text-vmta-teal prose-strong:text-vmta-teal prose-img:w-full prose-img:max-w-full prose-img:rounded-none">
            
            {!! $cleanBody !!}
        </div>

        @if(($relatedPosts ?? collect())->isNotEmpty())
            <section class="mt-12 border-t-2 border-vmta-teal pt-5">
                <h2 class="mb-5 font-sharp-bo text-[30px] font-bold uppercase leading-none text-vmta-teal">
                    {{ $locale === 'vi' ? 'Có thể bạn quan tâm' : 'You may also like' }}
                </h2>
                <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
                    @foreach($relatedPosts as $relatedPost)
                        @php
                            $relatedTranslation = $postTranslation($relatedPost);
                            $relatedImage = $postImage($relatedPost, $relatedTranslation);
                            $relatedUrl = $postUrl($relatedTranslation);
                            $relatedDate = $relatedPost->published_at?->format('d/m/Y');
                            $relatedExcerpt = $relatedTranslation?->excerpt
                                ?: \Illuminate\Support\Str::limit(strip_tags($relatedTranslation?->body ?? ''), 220);
                        @endphp
                        <article class="flex flex-col">
                            <a href="{{ $relatedUrl }}" class="block overflow-hidden bg-[#d4eceb]" aria-label="{{ $relatedTranslation?->title }}">
                                <img src="{{ $relatedImage }}" alt="{{ $relatedTranslation?->title }}" class="aspect-[16/9] w-full object-cover" loading="lazy" decoding="async">
                            </a>
                            <h3 class="mt-3 text-[18px] font-bold leading-[1.3] text-vmta-teal">
                                <a href="{{ $relatedUrl }}" class="text-vmta-teal hover:underline">
                                    {{ $relatedTranslation?->title }}
                                </a>
                            </h3>
                            @if($relatedExcerpt)
                                <p class="mt-2 text-[15px] leading-[1.55] text-vmta-teal/85">
                                    {{ $relatedExcerpt }}
                                </p>
                            @endif
                            <div class="mt-3 flex items-center justify-between text-[14px] text-vmta-teal">
                                <a href="{{ $relatedUrl }}" class="font-semibold text-vmta-teal hover:underline">
                                    {{ $locale === 'vi' ? 'Xem thêm' : 'Read more' }} &gt;
                                </a>
                                @if($relatedDate)
                                    <time datetime="{{ $relatedPost->published_at->toIso8601String() }}" class="text-vmta-teal/70">
                                        {{ $relatedDate }}
                                    </time>
                                @endif
                            </div>
                        </article>
                    @endforeach
                </div>
            </section>
        @endif
    </div>
</article>
@endsection

@if($hasHlsVideo)
@push('scripts')
    @vite('resources/js/hls-bootstrap.js')
@endpush
@endif
